[infra] Missing hdf5 dependency
Otherwise I get this

```
ld: eos_propagate_uncertainty-eos-propagate-uncertainty.o: undefined reference to symbol 'H5check_version'
ld: [...]/libhdf5.so.100.1.0: error adding symbols: DSO missing from command line
```